# Generated by Django 6.0.4 on 2026-05-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RECEPCION PARCIAL', 'Recepción Parcial'), ('RECEPCION OK', 'Recepción OK')], default='PENDIENTE', max_length=20),
        ),
    ]
