# Generated by Django 6.0.4 on 2026-05-07 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_ordencompra_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('idProyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='ingreso',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.proyecto'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.proyecto'),
        ),
        migrations.AddField(
            model_name='salida',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.proyecto'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='proyecto',
            field=models.ForeignKey(blank=True, help_text='Proyecto al que está asignado el usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.proyecto'),
        ),
        migrations.CreateModel(
            name='StockProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_proyecto', to='inventory.producto')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='inventory.proyecto')),
            ],
            options={
                'unique_together': {('producto', 'proyecto')},
            },
        ),
    ]
