# Generated by Django 6.0.4 on 2026-05-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_proyecto_ingreso_proyecto_ordencompra_proyecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='pro_crear',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='pro_editar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='pro_eliminar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='pro_ver',
            field=models.BooleanField(default=True),
        ),
    ]
