# Generated by Django 6.0.4 on 2026-05-07 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_permiso_pro_crear_permiso_pro_editar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='tra_crear',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='tra_eliminar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='tra_recibir',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='tra_ver',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('idTransferencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_despacho', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('EN TRANSITO', 'En Tránsito'), ('RECEPCION PARCIAL', 'Recepción Parcial'), ('RECEPCION OK', 'Recepción OK')], default='EN TRANSITO', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('proyecto_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to='inventory.proyecto')),
                ('proyecto_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despachos', to='inventory.proyecto')),
                ('usuario_despacha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleTransferencia',
            fields=[
                ('idDetalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_enviada', models.IntegerField()),
                ('cantidad_recibida', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.producto')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventory.transferencia')),
            ],
        ),
    ]
