# Generated by Django 6.0.4 on 2026-05-11 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_permiso_tra_crear_permiso_tra_eliminar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='trab_crear',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='trab_editar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='trab_eliminar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='trab_ver',
            field=models.BooleanField(default=True),
        ),
    ]
