# Generated by Django 6.0.4 on 2026-05-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_add_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('idBodega', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='ingreso',
            name='ingreso_fecha_idx',
        ),
        migrations.RemoveIndex(
            model_name='ordencompra',
            name='oc_estado_idx',
        ),
        migrations.RemoveIndex(
            model_name='ordencompra',
            name='oc_fecha_idx',
        ),
        migrations.RemoveIndex(
            model_name='producto',
            name='producto_nombre_idx',
        ),
        migrations.RemoveIndex(
            model_name='proveedor',
            name='proveedor_nombre_idx',
        ),
        migrations.RemoveIndex(
            model_name='salida',
            name='salida_fecha_idx',
        ),
        migrations.RemoveIndex(
            model_name='transferencia',
            name='transferencia_estado_idx',
        ),
    ]
