# Generated by Django 6.0.4 on 2026-05-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_bodega_remove_ingreso_ingreso_fecha_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='numCompra',
            field=models.CharField(max_length=100, unique=True, verbose_name='Número de Orden'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='idCompra',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]

    def apply(self, project_state, schema_editor, collect_sql=False):
        if schema_editor.connection.vendor == 'postgresql':
            for operation in self.operations:
                operation.state_forwards(self.app_label, project_state)
            with schema_editor.connection.cursor() as cursor:
                # Find all foreign keys pointing to inventory_ordencompra
                cursor.execute("""
                    SELECT 
                        tc.table_name, 
                        tc.constraint_name
                    FROM 
                        information_schema.table_constraints AS tc 
                        JOIN information_schema.key_column_usage AS kcu
                          ON tc.constraint_name = kcu.constraint_name
                          AND tc.table_schema = kcu.table_schema
                        JOIN information_schema.constraint_column_usage AS ccu
                          ON ccu.constraint_name = tc.constraint_name
                          AND ccu.table_schema = ccu.table_schema
                    WHERE 
                        tc.constraint_type = 'FOREIGN KEY' 
                        AND ccu.table_name = 'inventory_ordencompra'
                        AND ccu.table_schema = 'public';
                """)
                constraints = cursor.fetchall()
                for table_name, constraint_name in constraints:
                    cursor.execute(f'ALTER TABLE "{table_name}" DROP CONSTRAINT "{constraint_name}";')

                # Drop primary key constraint on inventory_ordencompra
                cursor.execute("""
                    SELECT constraint_name 
                    FROM information_schema.table_constraints 
                    WHERE table_name = 'inventory_ordencompra' 
                      AND constraint_type = 'PRIMARY KEY'
                      AND table_schema = 'public';
                """)
                pk_constraint = cursor.fetchone()
                if pk_constraint:
                    cursor.execute(f'ALTER TABLE "inventory_ordencompra" DROP CONSTRAINT "{pk_constraint[0]}";')

                # Drop identity/default sequence from numCompra so it can be altered to varchar
                cursor.execute('ALTER TABLE "inventory_ordencompra" ALTER COLUMN "numCompra" DROP IDENTITY IF EXISTS;')
                cursor.execute('ALTER TABLE "inventory_ordencompra" ALTER COLUMN "numCompra" DROP DEFAULT;')

                # Alter numCompra type to varchar(100)
                cursor.execute('ALTER TABLE "inventory_ordencompra" ALTER COLUMN "numCompra" TYPE varchar(100);')
                cursor.execute('ALTER TABLE "inventory_ordencompra" ADD CONSTRAINT "inventory_ordencompra_numCompra_key" UNIQUE ("numCompra");')

                # Add idCompra as serial primary key
                cursor.execute('ALTER TABLE "inventory_ordencompra" ADD COLUMN "idCompra" serial PRIMARY KEY;')

                # Recreate foreign key constraints pointing to idCompra
                for table_name, constraint_name in constraints:
                    cursor.execute(f"""
                        ALTER TABLE "{table_name}" 
                        ADD CONSTRAINT "{constraint_name}" 
                        FOREIGN KEY ("orden_compra_id") 
                        REFERENCES "inventory_ordencompra" ("idCompra") 
                        DEFERRABLE INITIALLY DEFERRED;
                    """)
            return project_state
        else:
            return super().apply(project_state, schema_editor, collect_sql)

    def unapply(self, project_state, schema_editor, collect_sql=False):
        if schema_editor.connection.vendor == 'postgresql':
            with schema_editor.connection.cursor() as cursor:
                # 1. Drop foreign keys pointing to idCompra
                cursor.execute("""
                    SELECT 
                        tc.table_name, 
                        tc.constraint_name
                    FROM 
                        information_schema.table_constraints AS tc 
                        JOIN information_schema.key_column_usage AS kcu
                          ON tc.constraint_name = kcu.constraint_name
                          AND tc.table_schema = kcu.table_schema
                        JOIN information_schema.constraint_column_usage AS ccu
                          ON ccu.constraint_name = tc.constraint_name
                          AND ccu.table_schema = ccu.table_schema
                    WHERE 
                        tc.constraint_type = 'FOREIGN KEY' 
                        AND ccu.table_name = 'inventory_ordencompra'
                        AND ccu.table_schema = 'public';
                """)
                constraints = cursor.fetchall()
                for table_name, constraint_name in constraints:
                    cursor.execute(f'ALTER TABLE "{table_name}" DROP CONSTRAINT "{constraint_name}";')

                # 2. Drop primary key constraint on idCompra
                cursor.execute("""
                    SELECT constraint_name 
                    FROM information_schema.table_constraints 
                    WHERE table_name = 'inventory_ordencompra' 
                      AND constraint_type = 'PRIMARY KEY'
                      AND table_schema = 'public';
                """)
                pk_constraint = cursor.fetchone()
                if pk_constraint:
                    cursor.execute(f'ALTER TABLE "inventory_ordencompra" DROP CONSTRAINT "{pk_constraint[0]}";')

                # 3. Drop column idCompra
                cursor.execute('ALTER TABLE "inventory_ordencompra" DROP COLUMN "idCompra";')

                # 4. Drop unique constraint on numCompra
                cursor.execute('ALTER TABLE "inventory_ordencompra" DROP CONSTRAINT IF EXISTS "inventory_ordencompra_numCompra_key";')

                # 5. Alter numCompra back to integer, make it an identity column, and set as primary key
                cursor.execute('ALTER TABLE "inventory_ordencompra" ALTER COLUMN "numCompra" TYPE integer USING "numCompra"::integer;')
                cursor.execute('ALTER TABLE "inventory_ordencompra" ALTER COLUMN "numCompra" ADD GENERATED BY DEFAULT AS IDENTITY;')
                cursor.execute('ALTER TABLE "inventory_ordencompra" ADD PRIMARY KEY ("numCompra");')

                # 6. Recreate foreign key constraints pointing to numCompra
                for table_name, constraint_name in constraints:
                    cursor.execute(f"""
                        ALTER TABLE "{table_name}" 
                        ADD CONSTRAINT "{constraint_name}" 
                        FOREIGN KEY ("orden_compra_id") 
                        REFERENCES "inventory_ordencompra" ("numCompra") 
                        DEFERRABLE INITIALLY DEFERRED;
                    """)
            return project_state
        else:
            return super().unapply(project_state, schema_editor, collect_sql)

