# Generated by Django 6.0.4 on 2026-05-18 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_ordencompra_idcompra_alter_ordencompra_numcompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bodegas', to='inventory.proyecto'),
        ),
    ]
