# Generated by Django 6.0.4 on 2026-05-19 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_bodega_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='proyectos_asignados',
            field=models.ManyToManyField(blank=True, help_text='Proyectos adicionales a los que el usuario tiene acceso', related_name='usuarios_asignados', to='inventory.proyecto'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='proyecto',
            field=models.ForeignKey(blank=True, help_text='Proyecto al que está asignado el usuario por defecto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.proyecto'),
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('idHerramienta', models.AutoField(primary_key=True, serialize=False)),
                ('nomHerramienta', models.CharField(max_length=255, verbose_name='Nombre Herramienta')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('marca', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo')], default='BUENO', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('en_reparacion', models.BooleanField(default=False)),
                ('bodega_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herramientas', to='inventory.bodega')),
            ],
        ),
        migrations.CreateModel(
            name='MantenimientoHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateField(auto_now_add=True)),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='inventory.herramienta')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('idMaquinaria', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_maquina', models.CharField(choices=[('MANITOU', 'Manitou'), ('BOBCAT_S650', 'Bobcat S-650'), ('BOBCAT_S770', 'Bobcat S770'), ('GRUA_HORQUILLA', 'Grúa Horquilla'), ('CAMION', 'Camión')], max_length=50)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('patente_o_codigo', models.CharField(max_length=100, unique=True)),
                ('tipo_control', models.CharField(choices=[('HORAS', 'Horómetro'), ('KILOMETROS', 'Kilometraje')], max_length=20)),
                ('valor_actual', models.IntegerField(default=0, help_text='Horas o Kilómetros actuales')),
                ('ultimo_mantenimiento', models.IntegerField(default=0, help_text='Valor en el que se hizo el último mantenimiento')),
                ('en_reparacion', models.BooleanField(default=False)),
                ('bodega_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquinarias', to='inventory.bodega')),
            ],
        ),
        migrations.CreateModel(
            name='MantenimientoMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateField(auto_now_add=True)),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('valor_mantenimiento', models.IntegerField(help_text='Horas o Kilómetros al momento del mantenimiento')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.proveedor')),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='inventory.maquinaria')),
            ],
        ),
        migrations.CreateModel(
            name='TransferenciaActivo',
            fields=[
                ('idTransferencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_despacho', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('EN TRANSITO', 'En Tránsito'), ('RECEPCION OK', 'Recepción OK')], default='EN TRANSITO', max_length=20)),
                ('tipo_activo', models.CharField(choices=[('HERRAMIENTA', 'Herramienta'), ('MAQUINARIA', 'Maquinaria')], max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('bodega_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepciones_activos', to='inventory.bodega')),
                ('bodega_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despachos_activos', to='inventory.bodega')),
                ('herramienta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.herramienta')),
                ('maquinaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.maquinaria')),
                ('usuario_despacha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
