# Generated by Django 6.0.4 on 2026-05-21 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_permiso_gdi_crear_permiso_gdi_editar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='maquinaria',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mantenimientomaquinaria',
            name='valor_mantenimiento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='ultimo_mantenimiento',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='valor_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='proyecto',
            field=models.ForeignKey(blank=True, help_text='Proyecto por defecto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.proyecto'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='proyectos_asignados',
            field=models.ManyToManyField(blank=True, help_text='Otros proyectos', related_name='usuarios_asignados', to='inventory.proyecto'),
        ),
        migrations.CreateModel(
            name='HistorialMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=255)),
                ('modulo', models.CharField(max_length=100)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Permiso',
        ),
    ]
