# Generated by Django 6.0.4 on 2026-05-21 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_bodega_activo_categoria_activo_herramienta_activo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('idPermiso', models.AutoField(primary_key=True, serialize=False)),
                ('cat_ver', models.BooleanField(default=True)),
                ('cat_crear', models.BooleanField(default=True)),
                ('cat_editar', models.BooleanField(default=True)),
                ('cat_eliminar', models.BooleanField(default=True)),
                ('prod_ver', models.BooleanField(default=True)),
                ('prod_crear', models.BooleanField(default=True)),
                ('prod_editar', models.BooleanField(default=True)),
                ('prod_eliminar', models.BooleanField(default=True)),
                ('prov_ver', models.BooleanField(default=True)),
                ('prov_crear', models.BooleanField(default=True)),
                ('prov_editar', models.BooleanField(default=True)),
                ('prov_eliminar', models.BooleanField(default=True)),
                ('ord_ver', models.BooleanField(default=True)),
                ('ord_crear', models.BooleanField(default=True)),
                ('ord_editar', models.BooleanField(default=True)),
                ('ord_eliminar', models.BooleanField(default=True)),
                ('ing_ver', models.BooleanField(default=True)),
                ('ing_crear', models.BooleanField(default=True)),
                ('ing_editar', models.BooleanField(default=True)),
                ('ing_eliminar', models.BooleanField(default=True)),
                ('sal_ver', models.BooleanField(default=True)),
                ('sal_crear', models.BooleanField(default=True)),
                ('sal_editar', models.BooleanField(default=True)),
                ('sal_eliminar', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
