from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_fix_esadmin_and_create_permisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='pro_ver',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='pro_crear',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='pro_editar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='pro_eliminar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='trab_ver',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='trab_crear',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='trab_editar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='trab_eliminar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='tra_ver',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='tra_crear',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='tra_recibir',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='tra_eliminar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='herr_ver',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='herr_crear',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='herr_editar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='herr_eliminar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='maq_ver',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='maq_crear',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='maq_editar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='maq_eliminar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='gdi_ver',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='gdi_crear',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='gdi_editar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='gdi_eliminar',
            field=models.BooleanField(default=True),
        ),
    ]
