# Generated by Django 6.0.4 on 2026-05-26 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='usuario_recibe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_recibidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
