# Generated by Django 6.0.4 on 2026-05-26 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_fix_ordencompra_foreign_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos', to='inventory.bodega'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='inventory.bodega'),
        ),
        migrations.AddField(
            model_name='salida',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas', to='inventory.bodega'),
        ),
    ]
