# Generated by Django 6.0.4 on 2026-05-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_trabajador_cargo_sueldo_modulo_torre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='cargo',
            field=models.CharField(choices=[('JEFE DE TERRENO', 'Jefe de Terreno'), ('ADMINISTRADOR DE OBRA', 'Administrador de obra'), ('ENCARGADO DE RECURSOS', 'Encargado de recursos'), ('BODEGUERO', 'Bodeguero'), ('OTRO', 'Otro')], default='OTRO', max_length=100),
        ),
    ]
