# Generated by Django 6.0.4 on 2026-06-06 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_permiso_mant_herr_mant_maq'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='gasto_crear',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='gasto_editar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='gasto_eliminar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='gasto_ver',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('idGasto', models.AutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(choices=[('PETROLEO', 'Petroleo'), ('BENCINA', 'Bencina'), ('MANO_OBRA', 'Mano de obra'), ('SUELDOS', 'Sueldos'), ('OTRO', 'Otro')], max_length=30)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('maquinaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='inventory.maquinaria', verbose_name='Vehiculo / Maquinaria')),
            ],
            options={
                'ordering': ['-fecha', '-idGasto'],
            },
        ),
    ]
