# Generated by Django 6.0.4 on 2026-06-06 21:41
# Fix: migration 0026 set must_change_password=True for all existing users,
# including the admin. Reset it to False so existing users are not locked out.

from django.db import migrations


def reset_existing_users(apps, schema_editor):
    Usuario = apps.get_model('inventory', 'Usuario')
    Usuario.objects.all().update(must_change_password=False)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_gasto_permisos_must_change_password'),
    ]

    operations = [
        migrations.RunPython(reset_existing_users, migrations.RunPython.noop),
    ]
