# Generated by Django 6.0.4 on 2026-06-06 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_historial_expand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialmovimiento',
            options={'ordering': ['-fecha'], 'verbose_name': 'Historial de movimiento', 'verbose_name_plural': 'Historial de movimientos'},
        ),
    ]
