# Generated by Django 6.0.4 on 2026-06-07 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_historialmovimiento_bodega'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('idFase', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='gasto',
            name='modulo_torre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='inventory.modulotorre', verbose_name='Modulo / Torre'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='inventory.trabajador', verbose_name='Trabajador'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='fase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='inventory.fase', verbose_name='Fase'),
        ),
    ]
