# Generated by Django 6.0.4 on 2026-06-10 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_add_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='orden_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.ordencompra'),
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='stockproyecto',
            options={'ordering': ['producto__nombre']},
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
