# Generated by Django 6.0.4 on 2026-06-17 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0033_ingreso_oc_opcional"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="proveedor",
            options={"ordering": ["nombre"]},
        ),
        migrations.CreateModel(
            name="SesionActiva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sesion_activa",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
