# Generated by Django 6.0.4 on 2026-06-18 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0034_alter_proveedor_options_sesionactiva"),
    ]

    operations = [
        migrations.AddField(
            model_name="gasto",
            name="archivo_respaldo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="gastos_respaldo/",
                verbose_name="Boleta / Factura",
            ),
        ),
        migrations.AddField(
            model_name="gasto",
            name="num_documento",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="N° Documento"
            ),
        ),
        migrations.AddField(
            model_name="gasto",
            name="proyecto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gastos",
                to="inventory.proyecto",
                verbose_name="Proyecto",
            ),
        ),
        migrations.AddField(
            model_name="gasto",
            name="tipo_documento",
            field=models.CharField(
                blank=True,
                choices=[("FACTURA", "Factura"), ("BOLETA", "Boleta")],
                max_length=10,
                null=True,
                verbose_name="Tipo Documento",
            ),
        ),
    ]
