# Generated by Django 6.0.4 on 2026-06-20 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_gasto_archivo_respaldo_gasto_num_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulotorre',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modulos_torre', to='inventory.proyecto'),
        ),
        migrations.AlterField(
            model_name='modulotorre',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='modulotorre',
            unique_together={('nombre', 'proyecto')},
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('idPartida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='inventory.proyecto')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'proyecto')},
            },
        ),
        migrations.AddField(
            model_name='salida',
            name='partida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas', to='inventory.partida'),
        ),
    ]
