# Generated by Django 6.0.4 on 2026-06-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_modulotorre_proyecto_alter_modulotorre_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='item_serviu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Item SERVIU'),
        ),
    ]
