# Generated by Django 6.0.4 on 2026-06-24 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_decimal_quantities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='transferenciaactivo',
            name='estado',
            field=models.CharField(choices=[('EN TRANSITO', 'En Tránsito'), ('RECEPCION PARCIAL', 'Recepción Parcial'), ('RECEPCION OK', 'Recepción OK')], default='EN TRANSITO', max_length=20),
        ),
        migrations.AlterField(
            model_name='transferenciaactivo',
            name='tipo_activo',
            field=models.CharField(blank=True, choices=[('HERRAMIENTA', 'Herramienta'), ('MAQUINARIA', 'Maquinaria')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='DetalleTransferenciaActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_activo', models.CharField(choices=[('HERRAMIENTA', 'Herramienta'), ('MAQUINARIA', 'Maquinaria')], max_length=20)),
                ('recibido', models.BooleanField(default=False)),
                ('herramienta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_transferencia', to='inventory.herramienta')),
                ('maquinaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_transferencia', to='inventory.maquinaria')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_activos', to='inventory.transferenciaactivo')),
            ],
        ),
    ]
