# Generated by Django 6.0.4 on 2026-06-29 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_migrate_transferenciaactivo_to_detalles'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='plan_crear',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='plan_editar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='plan_eliminar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='plan_ver',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio'),
        ),
        migrations.CreateModel(
            name='TareaPlanificacion',
            fields=[
                ('idTarea', models.AutoField(primary_key=True, serialize=False)),
                ('wbs_orden', models.PositiveSmallIntegerField(default=0)),
                ('nivel', models.PositiveSmallIntegerField(default=0)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('progreso', models.PositiveSmallIntegerField(default=0)),
                ('es_hito', models.BooleanField(default=False, verbose_name='Es Hito')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CURSO', 'En curso'), ('COMPLETADA', 'Completada'), ('BLOQUEADA', 'Bloqueada')], default='PENDIENTE', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtareas', to='inventory.tareaplanificacion')),
                ('partida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_planificacion', to='inventory.partida')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_planificacion', to='inventory.proyecto')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_planificacion', to='inventory.trabajador')),
            ],
            options={
                'verbose_name': 'Tarea de Planificación',
                'verbose_name_plural': 'Tareas de Planificación',
                'ordering': ['proyecto', 'wbs_orden', 'nivel', 'idTarea'],
            },
        ),
        migrations.CreateModel(
            name='DependenciaTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FS', 'Fin-Inicio (FS)'), ('SS', 'Inicio-Inicio (SS)'), ('FF', 'Fin-Fin (FF)')], default='FS', max_length=2)),
                ('tarea_predecesora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucesoras', to='inventory.tareaplanificacion')),
                ('tarea_sucesora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecesoras', to='inventory.tareaplanificacion')),
            ],
            options={
                'unique_together': {('tarea_sucesora', 'tarea_predecesora')},
            },
        ),
    ]
