# Generated by Django 6.0.4 on 2026-06-29 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_permiso_plan_crear_permiso_plan_editar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareaplanificacion',
            name='modulo_torre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_planificacion', to='inventory.modulotorre', verbose_name='Módulo / Torre'),
        ),
    ]
