# Generated by Django 6.0.4 on 2026-07-09 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_add_modulo_torre_to_tarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunes', models.BooleanField(default=True)),
                ('martes', models.BooleanField(default=True)),
                ('miercoles', models.BooleanField(default=True)),
                ('jueves', models.BooleanField(default=True)),
                ('viernes', models.BooleanField(default=True)),
                ('sabado', models.BooleanField(default=False)),
                ('domingo', models.BooleanField(default=False)),
                ('hora_inicio', models.TimeField(default='08:00')),
                ('hora_fin', models.TimeField(default='17:00')),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendario', to='inventory.proyecto')),
            ],
            options={
                'verbose_name': 'Calendario de Proyecto',
            },
        ),
        migrations.CreateModel(
            name='FeriadoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nombre', models.CharField(max_length=100)),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feriados', to='inventory.calendarioproyecto')),
            ],
            options={
                'verbose_name': 'Feriado',
                'ordering': ['fecha'],
                'unique_together': {('calendario', 'fecha')},
            },
        ),
    ]
