# Generated by Django 6.0.4 on 2026-07-23 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_calendario_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='concepto',
            field=models.CharField(choices=[('PETROLEO', 'Petroleo'), ('BENCINA', 'Bencina'), ('MANO_OBRA', 'Mano de obra'), ('SUELDOS', 'Sueldos'), ('MATERIALES', 'Materiales'), ('OTRO', 'Otro')], max_length=30),
        ),
        migrations.CreateModel(
            name='GastoDetalleMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precio_unit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_material', to='inventory.gasto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.producto')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
